### ISSUE TITLE
schema (WIP)

### ISSUE THREAD

**Issue by sidewinder2020** [sidewinder2020/bike-share#4]

**Comment by vaidashi** [comment]
![Screen Shot 2017-08-18 at 11.41.54 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/592dacd5c172ec00208ec435/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455fb6b7191a379ee0c2f50415a4abc30254d58eeb9cb74fce36f34985619e8d8645974c33944faebd01cba07ba208d4e87b3b88f4593fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be24d5da0113f6ae571336e0a.png)

**Comment by vaidashi** [comment]
Proposal: we would have to override the station names in trips before migrating , but it should keep the references to the stations table

**Comment by sidewinder2020** [comment]
I like the schema, but I'm thinking agile would be a great approach here.  Go through the iterations, and tweak as necessary.  Mods shouldn't be too difficult to implement, at the very least lend good practice with migrations
